name: Roy Kelleners
favicon: null
layout_spectrum: 0.12315725022926927
typography_spectrum: 0.660389460157603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.25185838527977467
  lightness: 0.17182509554550052
  saturation: 0.6268144950736314
  rhythmicContrast: 0.5741237280890346
purpose: []
